---
driver:
  name: vagrant

driver_config:
  require_chef_omnibus: true

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-13.10
    driver_config:
      box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_ubuntu-13.10_chef-provisionerless.box

suites:
  - name: default
    run_list:
      - recipe[rax-docker::aufs]
      - recipe[docker::default]
      - recipe[rax-docker::default]
    attributes:
      rax-docker:
        image: busybox
        command:
          name: sleep
          params: 5
